services:
  mysql:
    image: mysql:8.0.36
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bdk
      MYSQL_DATABASE: db_bdk
    ports:
      - "3306:3306"
    volumes:
      - db_bdk-mysql-data:/var/lib/mysql

volumes:
  db_bdk-mysql-data: