insert into course (external_id, name) values (UUID(), 'Administração');
insert into course (external_id, name) values (UUID(), 'Administração Pública');
insert into course (external_id, name) values (UUID(), 'Agroecologia');
insert into course (external_id, name) values (UUID(), 'Agronegócio');
insert into course (external_id, name) values (UUID(), 'Agronomia');
insert into course (external_id, name) values (UUID(), 'Análise de Sistemas');
insert into course (external_id, name) values (UUID(), 'Antropologia');
insert into course (external_id, name) values (UUID(), 'Arquitetura e Urbanismo');
insert into course (external_id, name) values (UUID(), 'Arquivologia');
insert into course (external_id, name) values (UUID(), 'Artes');
insert into course (external_id, name) values (UUID(), 'Artes Cênicas');
insert into course (external_id, name) values (UUID(), 'Astronomia');
insert into course (external_id, name) values (UUID(), 'Biblioteconomia');
insert into course (external_id, name) values (UUID(), 'Biologia');
insert into course (external_id, name) values (UUID(), 'Biomedicina');
insert into course (external_id, name) values (UUID(), 'Bioquímica');
insert into course (external_id, name) values (UUID(), 'Canto');
insert into course (external_id, name) values (UUID(), 'Cenografia');
insert into course (external_id, name) values (UUID(), 'Ciência da Computação');
insert into course (external_id, name) values (UUID(), 'Ciências Biológicas');
insert into course (external_id, name) values (UUID(), 'Ciências Contábeis');
insert into course (external_id, name) values (UUID(), 'Ciências Econômicas');
insert into course (external_id, name) values (UUID(), 'Ciências Sociais');
insert into course (external_id, name) values (UUID(), 'Cinema e Audiovisual');
insert into course (external_id, name) values (UUID(), 'Composição e Regência');
insert into course (external_id, name) values (UUID(), 'Computação');
insert into course (external_id, name) values (UUID(), 'Comunicação e Marketing');
insert into course (external_id, name) values (UUID(), 'Comunicação Social');
insert into course (external_id, name) values (UUID(), 'Desenho Industrial');
insert into course (external_id, name) values (UUID(), 'Design');
insert into course (external_id, name) values (UUID(), 'Design de Ambientes');
insert into course (external_id, name) values (UUID(), 'Design de Games');
insert into course (external_id, name) values (UUID(), 'Design de Interiores');
insert into course (external_id, name) values (UUID(), 'Design de Moda');
insert into course (external_id, name) values (UUID(), 'Design de Produto');
insert into course (external_id, name) values (UUID(), 'Design Digital');
insert into course (external_id, name) values (UUID(), 'Design Gráfico');
insert into course (external_id, name) values (UUID(), 'Direção');
insert into course (external_id, name) values (UUID(), 'Direito');
insert into course (external_id, name) values (UUID(), 'Educação Física');
insert into course (external_id, name) values (UUID(), 'Enfermagem');
insert into course (external_id, name) values (UUID(), 'Engenharia Acústica');
insert into course (external_id, name) values (UUID(), 'Engenharia Aeroespacial');
insert into course (external_id, name) values (UUID(), 'Engenharia Aeronáutica');
insert into course (external_id, name) values (UUID(), 'Engenharia Agrícola');
insert into course (external_id, name) values (UUID(), 'Engenharia Agroindustrial');
insert into course (external_id, name) values (UUID(), 'Engenharia Agronômica');
insert into course (external_id, name) values (UUID(), 'Engenharia Ambiental');
insert into course (external_id, name) values (UUID(), 'Engenharia Automotiva');
insert into course (external_id, name) values (UUID(), 'Engenharia Bioenergética');
insert into course (external_id, name) values (UUID(), 'Engenharia Biomédica');
insert into course (external_id, name) values (UUID(), 'Engenharia Bioquímica');
insert into course (external_id, name) values (UUID(), 'Engenharia Biotecnológica');
insert into course (external_id, name) values (UUID(), 'Engenharia Cartográfica');
insert into course (external_id, name) values (UUID(), 'Engenharia Civil');
insert into course (external_id, name) values (UUID(), 'Engenharia da Computação');
insert into course (external_id, name) values (UUID(), 'Engenharia da Mobilidade');
insert into course (external_id, name) values (UUID(), 'Engenharia de Agrimensura');
insert into course (external_id, name) values (UUID(), 'Engenharia de Agronegócios');
insert into course (external_id, name) values (UUID(), 'Engenharia de Alimentos');
insert into course (external_id, name) values (UUID(), 'Engenharia de Aquicultura');
insert into course (external_id, name) values (UUID(), 'Engenharia de Automação');
insert into course (external_id, name) values (UUID(), 'Engenharia de Bioprocessos');
insert into course (external_id, name) values (UUID(), 'Engenharia de Biossistemas');
insert into course (external_id, name) values (UUID(), 'Engenharia de Biotecnologia');
insert into course (external_id, name) values (UUID(), 'Engenharia de Energia');
insert into course (external_id, name) values (UUID(), 'Engenharia de Gestão');
insert into course (external_id, name) values (UUID(), 'Engenharia de Informação');
insert into course (external_id, name) values (UUID(), 'Engenharia de Instrumentação, Automação e Robótica');
insert into course (external_id, name) values (UUID(), 'Engenharia de Manufatura');
insert into course (external_id, name) values (UUID(), 'Engenharia de Materiais');
insert into course (external_id, name) values (UUID(), 'Engenharia de Minas');
insert into course (external_id, name) values (UUID(), 'Engenharia de Pesca');
insert into course (external_id, name) values (UUID(), 'Engenharia de Petróleo');
insert into course (external_id, name) values (UUID(), 'Engenharia de Produção');
insert into course (external_id, name) values (UUID(), 'Engenharia de Recursos Hídricos');
insert into course (external_id, name) values (UUID(), 'Engenharia de Saúde e Segurança');
insert into course (external_id, name) values (UUID(), 'Engenharia de Sistemas');
insert into course (external_id, name) values (UUID(), 'Engenharia de Software');
insert into course (external_id, name) values (UUID(), 'Engenharia de Telecomunicações');
insert into course (external_id, name) values (UUID(), 'Engenharia de Transporte e Logística');
insert into course (external_id, name) values (UUID(), 'Engenharia Elétrica');
insert into course (external_id, name) values (UUID(), 'Engenharia Eletrônica');
insert into course (external_id, name) values (UUID(), 'Engenharia em Sistemas Digitais');
insert into course (external_id, name) values (UUID(), 'Engenharia Ferroviária e Metroviária');
insert into course (external_id, name) values (UUID(), 'Engenharia Física');
insert into course (external_id, name) values (UUID(), 'Engenharia Florestal');
insert into course (external_id, name) values (UUID(), 'Engenharia Geológica');
insert into course (external_id, name) values (UUID(), 'Engenharia Hídrica');
insert into course (external_id, name) values (UUID(), 'Engenharia Industrial');
insert into course (external_id, name) values (UUID(), 'Engenharia Mecânica');
insert into course (external_id, name) values (UUID(), 'Engenharia Mecatrônica');
insert into course (external_id, name) values (UUID(), 'Engenharia Metalúrgica');
insert into course (external_id, name) values (UUID(), 'Engenharia Naval');
insert into course (external_id, name) values (UUID(), 'Engenharia Química');
insert into course (external_id, name) values (UUID(), 'Engenharia Têxtil');
insert into course (external_id, name) values (UUID(), 'Estatística');
insert into course (external_id, name) values (UUID(), 'Farmácia');
insert into course (external_id, name) values (UUID(), 'Filosofia');
insert into course (external_id, name) values (UUID(), 'Física');
insert into course (external_id, name) values (UUID(), 'Fisioterapia');
insert into course (external_id, name) values (UUID(), 'Fonoaudiologia');
insert into course (external_id, name) values (UUID(), 'Geografia');
insert into course (external_id, name) values (UUID(), 'Gestão Ambiental');
insert into course (external_id, name) values (UUID(), 'Gestão da Informação');
insert into course (external_id, name) values (UUID(), 'Gestão de Políticas Públicas');
insert into course (external_id, name) values (UUID(), 'Gestão de Serviços de Saúde');
insert into course (external_id, name) values (UUID(), 'Gestão do Agronegócio');
insert into course (external_id, name) values (UUID(), 'Gestão Pública');
insert into course (external_id, name) values (UUID(), 'História');
insert into course (external_id, name) values (UUID(), 'Hotelaria');
insert into course (external_id, name) values (UUID(), 'Jornalismo');
insert into course (external_id, name) values (UUID(), 'Letras');
insert into course (external_id, name) values (UUID(), 'Marketing');
insert into course (external_id, name) values (UUID(), 'Matemática');
insert into course (external_id, name) values (UUID(), 'Mecânica Industrial');
insert into course (external_id, name) values (UUID(), 'Medicina');
insert into course (external_id, name) values (UUID(), 'Medicina Veterinária');
insert into course (external_id, name) values (UUID(), 'Moda');
insert into course (external_id, name) values (UUID(), 'Música');
insert into course (external_id, name) values (UUID(), 'Nutrição');
insert into course (external_id, name) values (UUID(), 'Odontologia');
insert into course (external_id, name) values (UUID(), 'Pedagogia');
insert into course (external_id, name) values (UUID(), 'Políticas Públicas');
insert into course (external_id, name) values (UUID(), 'Propaganda e Marketing');
insert into course (external_id, name) values (UUID(), 'Psicologia');
insert into course (external_id, name) values (UUID(), 'Publicidade e Propaganda');
insert into course (external_id, name) values (UUID(), 'Química');
insert into course (external_id, name) values (UUID(), 'Rádio, TV e Internet');
insert into course (external_id, name) values (UUID(), 'Relações Internacionais');
insert into course (external_id, name) values (UUID(), 'Relações Públicas');
insert into course (external_id, name) values (UUID(), 'Secretariado Executivo');
insert into course (external_id, name) values (UUID(), 'Serviço Social');
insert into course (external_id, name) values (UUID(), 'Sistemas de Informação');
insert into course (external_id, name) values (UUID(), 'Tecnologias Digitais');
insert into course (external_id, name) values (UUID(), 'Teologia');
insert into course (external_id, name) values (UUID(), 'Terapia Ocupacional');
insert into course (external_id, name) values (UUID(), 'Tradutor e Intérprete');
insert into course (external_id, name) values (UUID(), 'Turismo');
insert into course (external_id, name) values (UUID(), 'Zootecnia');
